### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by ChainKiller** [fake-name/MangaCMS#4]
I tried to install this on a Debian 7 VPS, but i never worked with python before so i'm a little stuck.

I uploaded the MangaCMS file through ftp, installed postgresql 9.4, installed libtiff4-dev, zlib1g-dev liblcms2-dev, libwebp-dev, libxml2, libxslt1-dev (libjpeg-turbo8-dev i couldn't figure it out), i've [build Python 3.4.3](http://askubuntu.com/questions/244544/how-do-i-install-python-3-3) and  [phantomjs](http://phantomjs.org/build.html); but when i run installDeps.sh i get the following:

root@s1:/var/www/clients/client1/web1/web/mcms/setuptools# sudo ./installDeps.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.4
E: Couldn't find any package by regex 'python3.4'
E: Unable to locate package python3.4-dev
E: Couldn't find any package by regex 'python3.4-dev'
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package phantomjs
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libjpeg-turbo8-dev
--2015-03-01 14:02:28--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 185.31.19.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|185.31.19.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1608741 (1.5M) [text/x-python]
Saving to: `get-pip.py.2'

100%[=================================================>] 1,608,741   --.-K/s   in 0.1s

2015-03-01 14:02:28 (10.4 MB/s) - `get-pip.py.2' saved [1608741/1608741]

./installDeps.sh: line 20: python3: command not found
./installDeps.sh: line 25: pip3: command not found
./installDeps.sh: line 26: pip3: command not found
./installDeps.sh: line 27: pip3: command not found
./installDeps.sh: line 28: pip3: command not found
Reading package lists... Done
Building dependency tree
Reading state information... Done
gfortran is already the newest version.
liblapack-dev is already the newest version.
libopenblas-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
./installDeps.sh: line 37: pip3: command not found
sudo: pip3: command not found
sudo: pip3: command not found
sudo: pip3: command not found
sudo: pip3: command not found
ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/citext.control": No such file or directory
Increasing the number of inotify watches.
fs.inotify.max_user_watches = 524288
net.core.wmem_max = 12582912
net.core.rmem_max = 12582912
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.core.wmem_max = 12582912
net.core.rmem_max = 12582912
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.core.wmem_max = 12582912
net.core.rmem_max = 12582912
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_watches = 524288

**Comment by ChainKiller** [comment]
I think i managed to somehow install/configure it, i have some zip files downloaded.
How can i access the web interface though? I've run mainWeb.py but got no idea ho to access it, i tried to go to ip:8081 but i get 
`Index of /`
`[ICO]	Name	Last modified	Size	Description`
`Apache/2.4.10 (Ubuntu) Server at 178.62.213.51 Port 8081`

**Comment by fake-name** [comment]
Yeah, I'm not sure what's going on, but you're missing a whole pile of the packages required. You're going to have to go through `installDeps.sh` and fix any calls to apt-get so they work on debian (it's written for Ubuntu).

Furthermore, you somehow don't have python3 installed, or at least it's not on your `%PATH`, so all the python packages are missing (because `pip3` isn't installed, since it can't find the python3 install). 

It also looks like some of the postgresql extensions (`CITEXT`) are missing, probably because `postgresql-contrib` is called something else (it's a additional extension as part of a separate module).

Lastly, you appear to somehow have apache running on your server, which will break the web UI. The web UI is entirely served within python. You need to either stop apache from listening on port 8081, or change the port MangaCMS uses (edit `server.socket_port = 8081` in `webserver_process.py`).

Remember, neither of the components are daemonized, so if you run `python3 mainWeb.py` or `python3 mainScrape.py`, and it exits, it's not working.

**Comment by fake-name** [comment]
Also, if you're running your commands as root (`root@s1`), using sudo is irrelevant. You should probably create a non-root-user, and use that for everything.

**Comment by fake-name** [comment]
Debian [appears to have `python3.4` packages](https://packages.debian.org/search?keywords=python3.4), so it *looks* like you may just need to enable the `unstable` repository. [The same is true for phantomjs.](https://packages.debian.org/search?keywords=phantomjs)

**Comment by ChainKiller** [comment]
I will try it on ubuntu now.

**Comment by ChainKiller** [comment]
I give up :), to complicated for me. Not what i need anyway. Thanks for your time.
